server:
  port: 8088
spring:
  application:
    name: api-driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    port: 6379
    host: 192.168.183.130
    database: 1